# Generated by Django 2.1.5 on 2019-02-06 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('type', models.CharField(choices=[('office', 'Department Office'), ('chairman', 'Department Chairman'), ('accounts', 'Accounts Office'), ('provost', 'Hall Provost'), ('bank', 'Bank')], max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('code', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('credits', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('alias', models.CharField(max_length=16)),
                ('chairman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chairman', to='api.AdminUser')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officer', to='api.AdminUser')),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=16)),
                ('departments', models.ManyToManyField(to='api.Department')),
                ('provost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.AdminUser')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('courses', models.ManyToManyField(to='api.Course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('session', models.CharField(max_length=11)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=16)),
                ('date_of_birth', models.DateField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField(max_length=256)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Hall')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Semester')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('number', 'year', 'department')},
        ),
    ]
