# Generated by Django 2.1.5 on 2019-02-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190206_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='allowed_attendance',
            field=models.PositiveIntegerField(default=70),
        ),
        migrations.AlterField(
            model_name='exam',
            name='attendance_fine',
            field=models.PositiveIntegerField(default=600),
        ),
        migrations.AlterField(
            model_name='exam',
            name='fees_per_credit',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='exam',
            name='fined_attendance',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
