# Generated by Django 2.1.5 on 2019-02-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190206_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examform',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
