# Generated by Django 2.1.5 on 2019-02-07 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190206_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='religion',
            field=models.CharField(choices=[('islam', 'Islam'), ('hinduism', 'Hinduism'), ('christianity', 'Christianity'), ('buddhism', 'Buddhism'), ('other', 'Other')], default='islam', max_length=16),
            preserve_default=False,
        ),
    ]
