# Generated by Django 2.1.5 on 2019-02-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190207_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='ldo_payment',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='status',
            field=models.CharField(choices=[('b', 'Pending for attendance entry'), ('c', 'Pending for chairman approval'), ('d', 'Pending for fees imposure'), ('e', 'Pending for provost approval'), ('f', 'Pending for payment'), ('g', 'Payment completed')], default='b', max_length=1),
        ),
    ]
