# Generated by Django 2.1.5 on 2019-02-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20190208_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examform',
            name='attendance',
            field=models.SmallIntegerField(default=-1),
        ),
    ]
